name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set version
      id: set_version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"

    - name: Build
      run: make
